export default {
  login: "yousef-ghanim",
  id: 64266208,
  node_id: "MDQ6VXNlcjY0MjY2MjA4",
  avatar_url: "https://avatars.githubusercontent.com/u/64266208?v=4",
  gravatar_id: "",
  url: "https://api.github.com/users/yousef-ghanim",
  html_url: "https://github.com/yousef-ghanim",
  followers_url: "https://api.github.com/users/yousef-ghanim/followers",
  following_url:
    "https://api.github.com/users/yousef-ghanim/following{/other_user}",
  gists_url: "https://api.github.com/users/yousef-ghanim/gists{/gist_id}",
  starred_url:
    "https://api.github.com/users/yousef-ghanim/starred{/owner}{/repo}",
  subscriptions_url: "https://api.github.com/users/yousef-ghanim/subscriptions",
  organizations_url: "https://api.github.com/users/yousef-ghanim/orgs",
  repos_url: "https://api.github.com/users/yousef-ghanim/repos",
  events_url: "https://api.github.com/users/yousef-ghanim/events{/privacy}",
  received_events_url:
    "https://api.github.com/users/yousef-ghanim/received_events",
  type: "User",
  site_admin: false,
  name: "Yousef Ghanim",
  company: null,
  blog: "https://yghanim.com",
  location: "Iceland",
  email: null,
  hireable: null,
  bio: "I am a self-taught front-end developer. I build and develop websites using the latest modern development languages and tools.",
  twitter_username: "YusufGhanem",
  public_repos: 45,
  public_gists: 0,
  followers: 0,
  following: 0,
  created_at: "2020-04-24T13:29:33Z",
  updated_at: "2021-05-25T04:02:50Z",
};
